version: '3.8'

services:
  boading-app:
    build: 
      context: .
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - "${APP_PORT:-80}:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    
  # Development service (optional)
  boading-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - VITE_API_BASE_URL=${VITE_API_BASE_URL}
        - NODE_ENV=${NODE_ENV:-development}
    ports:
      - "${DEV_PORT:-3000}:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    env_file:
      - .env
    profiles:
      - dev
